import Link from "next/link"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{
          backgroundColor: "burlywood",
          padding: "1rem",
          textAlign:"center"
        }}>
          <nav style={{
            display:"flex",
            justifyContent:"space-evenly"
          }}>
            <Link href={'/about'}>About</Link>
            <Link href={'/contactInfo'}>Contact Info</Link>
            <Link href={'/countries'}>Countries</Link>
          </nav>
        </header>

        <div style={{
          padding: "10rem",
          textAlign:"center"
        }}>
          {children}
        </div>

        <footer style={{
          backgroundColor: "burlywood",
          textAlign:"center",
          padding:"1rem"
        }}>@travelDestinations.com</footer>
      </body>
    </html>
  )
}
